import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/design/layout/Header";
import { Footer } from "@/design/layout/Footer";
import SmoothScroll from "@/design/layout/SmoothScroll";
import "lenis/dist/lenis.css";
import BackToTop from "@/design/ui/BackToTop";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header />
        <SmoothScroll>
          {children}
          <BackToTop />
        </SmoothScroll>
        <Footer />
      </body>
    </html>
  );
}
